version: "3.9"

services:
  php-service:
    container_name: php-service
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    links:
      - mysql-service
    volumes:
      - ./:/var/www/html

  mysql-service:
    container_name: mysql-service
    image: mariadb:10.8.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=DIPLOM

  web-service:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - "./docker/web/:/etc/nginx/conf.d/"
      # - "./docker/web/default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - php-service
    ports:
      - "81:80"

  # frontend-service:
  #   build:
  #     context: .
  #     dockerfile: docker/front/Dockerfile
  #   working_dir: /var/www/html
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - php-service
  #   volumes:
  #     - ./:/var/www/html

  #   tty: true

  frontend-service:
    container_name: frontend-service
    image: node:lts
    working_dir: /var/www/html
    # entrypoint: bin/bash
    volumes:
      - ./:/var/www/html
      # - ./:/resources/js/app
    ports:
      - "3001:3000"
    tty: true
