version: "3.9"

services:
  php-service:
    container_name: php-service
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    links:
      - mysql-service
    volumes:
      - ./:/var/www/html

  mysql-service:
    container_name: mysql-service
    image: mariadb:10.8.3
    environment:
      # - MYSQL_ROOT_PASSWORD=
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=DIPLOM

  # mysql-service:
  #   container_name: mysql-service
  #   image: mysql:8.0.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD:
  #     MYSQL_PASSWORD:
  #     MYSQL_USER: "root"
  #     MYSQL_DATABASE: DIPLOM

  web-service:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - "./docker/web/:/etc/nginx/conf.d/"
    links:
      - php-service
    ports:
      - "81:80"

  frontend-service:
    container_name: frontend-service
    image: node:lts
    working_dir: /var/www/html

    volumes:
      - ./:/var/www/html
      - ./:/resources/js
    ports:
      - "3001:3000"
    tty: true
